// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGyc7Qdofoyz2lgD-Z9gTf4e79YxAADoI',
    appId: '1:644442202771:web:ed4530b41a6b808d3b6366',
    messagingSenderId: '644442202771',
    projectId: 'groom-c6593',
    authDomain: 'groom-c6593.firebaseapp.com',
    databaseURL: 'https://groom-c6593-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groom-c6593.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-vBAZLuzQg5LYhO6DfESkiahMbTmiLg',
    appId: '1:644442202771:android:17c8637904cc6a6b3b6366',
    messagingSenderId: '644442202771',
    projectId: 'groom-c6593',
    databaseURL: 'https://groom-c6593-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groom-c6593.appspot.com',
  );
}
